version: '2'
services:
  4strony-db:
    container_name: "4strony-db"
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=4analysis
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8732:3306
  4strony-webapp:
    container_name: "4strony-webapp"
    build: ./ifa-webapp
    environment:
      - MYSQL_URI=4strony-db:3306
      - MYSQL_DATABASE=4analysis
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8730:8080
      - 8731:9990
    depends_on:
      - 4strony-db
  4strony-reports-db:
    container_name: "4strony-reports-db"
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=4analysisReports
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8737:3306
  4strony-reports-api:
    container_name: "4strony-reports-api"
    build: ./ifa-reports
    environment:
      - MYSQL_URI=4strony-reports-db:3306
      - MYSQL_DATABASE=4analysisReports
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 8735:8080
      - 8736:9990
    depends_on:
      - 4strony-reports-db